# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

# tables will be filled automatically with job map info (from resource manager data)     
- table:
    name: jobnodemap
    options:
      update:
        LLgenDB: add_jobnodemap
        archive:
          non_existent: currentjobs/jobid # if table exists
      index: jobid
    columns: 
    - { name: jobid,       type: jobid_t }
    - { name: nodeid,      type: nodeid_t }
    - { name: perc,        type: perc_t } 

- table:
    name: jobtsmap
    options:
      update:
        LLgenDB: add_jobtsmap
      archive:
        non_existent: currentjobs/jobid # if table exists
      index: ts
    columns: 
    - { name: jobid,       type: jobid_t }
    - { name: ts,          type: ts_t }

