#!/usr/bin/bash
# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

# Note: file .llview_server_rc must be sourced, e.g.:
# $ source ~/.llview_server_rc

cm="ls -ltr $LLVIEW_DATA/$LLVIEW_SYSTEMNAME/logs/*errlog $LLVIEW_DATA/$LLVIEW_SYSTEMNAME/logs/steps/*errlog | nl"
eval ${cm}

while [ $# -gt 0 ] ; do
	case $1 in
		delete) echo "Deleting error files..." ; cd $LLVIEW_DATA/$LLVIEW_SYSTEMNAME ; find ./ -name *errlog -delete ; exit 0 ;;
		open)
			if [ -z "$2" ]; then
				echo "Please provide a line number for the file to open."
				exit 1
			fi
			line_number=$2
			file=$(eval $cm | sed -n "${line_number}p" | awk '{print $NF}')
			if [ -f "$file" ]; then
				vim "$file"
			else
				echo "File $file not found."
				exit 1
			fi
			exit 0
			;;
	esac
	shift
done
