#!/usr/bin/bash
# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Filipe Guimarães (Forschungszentrum Juelich GmbH) 

usage () {
cat << EOM
Follow tail of specific log and error files on $LLVIEW_DATA/$LLVIEW_SYSTEMNAME/{monitor,logs}/
Usage: $(basename "$0") [ monitor | (actionname) ]
EOM
}

if [[ $# -eq 0 ]]
then
  usage 
  exit 1
fi

# Note: file .llview_server_rc must be sourced, e.g.:
# $ source ~/.llview_server_rc

if [[ $1 == "monitor" ]]
then
  dir=$LLVIEW_DATA/$LLVIEW_SYSTEMNAME/monitor
else
  dir=$LLVIEW_DATA/$LLVIEW_SYSTEMNAME/logs
fi

shopt -s nullglob
files=($dir/$1.*`date +%Y.%m.%d`*)
echo ${#files[@]}
if [[ ${#files[@]} -eq 0 ]]
then
  echo "No files found for $1"
  exit 1
else
  echo "Tail: ${files[@]}"
  tail -f ${files[@]}
fi


