# Copyright (c) 2023 Forschungszentrum Juelich GmbH.
# This file is part of LLview. 
#
# This is an open source software distributed under the GPLv3 license. More information see the LICENSE file at the top level.
#
# Contributions must follow the Contributor License Agreement. More information see the CONTRIBUTING.md file at the top level.
#
# Contributors:
#    Wolfgang Frings (Forschungszentrum Juelich GmbH) 

DBstat:
  tables:
    
    - table:
        name: LMLDBstat
        options:
          update:
            LML: dbstat
          update_trigger:
            - LMLDBstatALL
          archive:
            limit: max(ts)-21d
        columns: 
          - { name: ts,        type: ts_t,               LML_from: ts,              LML_default: -1, LML_minlastinsert: mintsinserted        }
          - { name: ts_min,    type: ts_t,               LML_from: ts_min,          LML_default: -1 }
          - { name: ts_max,    type: ts_t,               LML_from: ts_max,          LML_default: -1 }
          - { name: ts_dur,    type: ts_t,               LML_from: ts_dur,          LML_default: -1 }
          - { name: db,        type: name_t,             LML_from: db,              LML_default: 'unknown' }
          - { name: tab,       type: name_t,             LML_from: table,           LML_default: "-" }
          - { name: tabpath,   type: name_t,             LML_from: tabpath,         LML_default: 'unknown' }
          - { name: nrows,     type: cnt_t,              LML_from: nrows,           LML_default: -1 }
          - { name: time_aggr_res, type: cnt_t,          LML_from: time_aggr_res,   LML_default: -1 }

    - table:
        name: LMLDBgraph
        options:
          update:
            LML: dbgraph
            mode: replace
          update_trigger:
          archive:
            limit: max(ts)-21d
        columns: 
          - { name: ts,        type: ts_t,               LML_from: ts,              LML_default: -1, LML_minlastinsert: mintsinserted        }
          - { name: db,        type: name_t,             LML_from: db,              LML_default: 'unknown' }
          - { name: ntabs,     type: cnt_t,              LML_from: ntabs,           LML_default: 0 }
          - { name: nlinks,    type: cnt_t,              LML_from: nlinks,          LML_default: 0 }
          - { name: LMLattr,   type: llongstr_t,         LML_from: LMLattr,           LML_default: "-" }
          - { name: graph,     type: extralongstr_t,     LML_from: graph,           LML_default: "-" }

    - table:
        name: LMLDBstatcurrent
        options:
          update:
            LML: dbstat
            mode: replace
        columns: 
          - { name: ts,        type: ts_t,               LML_from: ts,              LML_default: -1        }
          - { name: ts_min,    type: ts_t,               LML_from: ts_min,          LML_default: -1 }
          - { name: ts_max,    type: ts_t,               LML_from: ts_max,          LML_default: -1 }
          - { name: ts_dur,    type: ts_t,               LML_from: ts_dur,          LML_default: -1 }
          - { name: db,        type: name_t,             LML_from: db,              LML_default: 'unknown' }
          - { name: tab,       type: name_t,             LML_from: table,           LML_default: "-" }
          - { name: tabpath,   type: name_t,             LML_from: tabpath,         LML_default: 'unknown' }
          - { name: nrows,     type: cnt_t,              LML_from: nrows,           LML_default: -1 }
          - { name: time_aggr_res, type: cnt_t,          LML_from: time_aggr_res,   LML_default: -1 }
          
    - table:
        name: LMLDBstatALL
        options:
          update:
            sql_update_contents:
              vars: mintsinserted
              sql: DELETE FROM LMLDBstatALL WHERE (ts >= mintsinserted);
                   INSERT INTO LMLDBstatALL (ts,ts_min,ts_max,ts_dur,db,tab,tabpath,nrows)
                                        SELECT ts,MIN(ts_min),MIN(ts_max),MAX(ts_dur),
                                           "ALL","ALL","ALL/ALL",
                                           SUM(nrows)
                                           FROM LMLDBstat
                                           WHERE (ts >= mintsinserted)
                                           GROUP BY ts
              sqldebug: 0
          archive:
            limit: max(ts)-21d
        columns: 
          - { name: ts,        type: ts_t }
          - { name: ts_min,    type: ts_t }
          - { name: ts_max,    type: ts_t }
          - { name: ts_dur,    type: ts_t }
          - { name: db,        type: name_t }
          - { name: tab,       type: name_t }
          - { name: tabpath,   type: name_t }
          - { name: nrows,     type: cnt_t }
          
          
